version: '3'
services:
  deepspeech:
    image: kai5263499/diy-jarvis-deepspeech
    restart: always
    environment: 
      - MQTT_BROKER=tcp://diy-jarvis-mqtt:1883
      - LOG_LEVEL=debug
      - DEBUG
  mic-capture:
    image: kai5263499/diy-jarvis-mic-capture
    restart: always
    environment: 
      - MQTT_BROKER=tcp://diy-jarvis-mqtt:1883
      - LOG_LEVEL=debug
      - PULSE_CONFIG=~/.config/pulse
      - PULSE_SERVER=172.17.0.1
      - PULSE_DURATION-10s
      - AUDIO_CAPTURE_DURATION=3s
      - DEBUG
    volumes:
      - "~/.config/pulse:/home/pulseaudio/.config/pulse"
  diy-jarvis-mqtt:
    image: "eclipse-mosquitto:latest"
    restart: always
volumes:
  tmp-content:
  
