version: '3'
services:
  builder:
    image: kai5263499/diy-jarvis-deepspeech-builder
    build:
      context: .
      dockerfile: Dockerfile
  deepspeech-models:
    image: kai5263499/diy-jarvis-deepspeech-models
    build:
      context: .
      dockerfile: cmd/deepspeech/Dockerfile.model
  deepspeech:
    image: kai5263499/diy-jarvis-deepspeech
    environment: 
      - MQTT_BROKER=tcp://mqtt:1883
      - DEBUG
    build:
      context: .
      dockerfile: cmd/deepspeech/Dockerfile
  mic_capture:
    image: kai5263499/diy-jarvis-mic_capture
    environment: 
      - MQTT_BROKER=tcp://mqtt:1883
      - DEBUG
    build:
      context: .
      dockerfile: cmd/mic_capture/Dockerfile
  mqtt:
    image: "eclipse-mosquitto:latest"
    restart: always
volumes:
  tmp-content:
  
