version: '3.2'
services:  
  diy-jarvis-text-processor:
    image: kai5263499/diy-jarvis-text-processor
    container_name: diy-jarvis-text-processor
    ports:
      - "6001:6001"
    environment: 
      COMMAND_SPEC_YAML: "/data/commands.yaml"
    volumes:
        - type: bind
          source: ./cmd/text_processor/commands.yaml
          target: /data/commands.yaml
    deploy:
      restart_policy:
        condition: on-failure
  diy-jarvis-mic-capture:
    image: kai5263499/diy-jarvis-mic-capture
    container_name: diy-jarvis-mic-capture
    environment:
      PULSE_SERVER: "172.17.0.1"
      DURATION: 3
      AUDIO_PROCESSOR_ADDRESS: "172.17.0.1:6000"
    depends_on:
      - diy-jarvis-deepspeech
    volumes:
      - type: bind
        source: /home/wes/.config/pulse
        target: /home/pulseaudio/.config/pulse
    deploy:
      restart_policy:
        condition: on-failure
  diy-jarvis-deepspeech:
    image: kai5263499/diy-jarvis-deepspeech
    container_name: diy-jarvis-deepspeech
    environment: 
      TEXT_PROCESSOR_ADDRESS: "172.17.0.1:6001"
    depends_on: 
      - "diy-jarvis-text-processor"
    volumes:
        - type: bind
          source: /home/wes/Downloads/deepspeech-0.6.0-models
          target: /deepspeech_models
    ports:
      - "6000:6000"
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  modeldata: