version: '3'
services:
  deepspeech:
    image: kai5263499/diy-jarvis-deepspeech
    environment: 
      - MQTT_BROKER=tcp://mqtt:1883
      - DEBUG
      - MODEL=/deepspeech_models/deepspeech-0.8.2-models.pbmm
  mic_capture:
    image: kai5263499/diy-jarvis-mic_capture
    environment: 
      - MQTT_BROKER=tcp://mqtt:1883
      - DEBUG
      - PULSE_CONFIG=~/.config/pulse
      - PULSE_SERVER=172.17.0.1
  mqtt:
    image: "eclipse-mosquitto:latest"
    restart: always
volumes:
  tmp-content:
  
